### PR TITLE
Small changes to the procedure

### PR DESCRIPTION
**Pull request by srisi**
I also have a screenshot of the error produced when npm install does not show up.

### CODE REVIEW

**Comment by mscuthbert** [comment]
yep!

**Comment by ryaanahmed** [comment]
> I also have a screenshot of the error produced when npm install does not show up.

@srisi  -- do you mean the error that you get if you try the rest of the procedure (and get to running 'npm start') when this happens? If so, I don't think we need to show this error as part of the procedure but rather have an "if 'npm install' doesn't appear in the banner" step that involves actually doing it at the command line.

**Comment by srisi** [comment]
Yes. My first guess was that the banner didn't appear because I already had the necessary npm packages installed, which is why I skipped the step. 
I agree though, it's probably easiest to just say: if the banner doesn't appear, run npm install manually.

**Comment by ryaanahmed** [comment]
> I agree though, it's probably easiest to just say: if the banner doesn't appear, run npm install manually.

Yeah. I want to see if there's a way to force PyCharm to detect the deps, though, so we don't have to fall back to the command line. For Python deps, if you open the ```requirements.txt``` file, PyCharm does a check. Perhaps there's something similar for the ```package.json``` file. #6

**Pull request merged**
